<?php
namespace app;

use Exception;
use think\exception\Handle;

class VrException extends Handle{

    public function render(Exception $e)
    {
//        return parent::render($e); // TODO: Change the autogenerated stub
        if(config('app_debug')){
            return parent::render($e);
        }else{
            header("Location: ".$_SERVER['REQUEST_SCHEME'].'://'.$_SERVER['HTTP_HOST'].'/404.html');
        }
    }
}
